/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Leticia
 */
import java.sql.*;
import ConnectionFactory.ConnectionFactory;
import com.sun.glass.events.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import ClassModel.Usuario_Class;
import java.awt.Color;

public class Form_Login extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    private String nome;
    private Connection conn = null;
    private Statement stm = null;
    private ResultSet rs = null;
    private PreparedStatement pstm = null;
    
    public String getNome(){
        return nome;
    }
    
    public void setNome (String nome){
        this.nome = nome;
    }
    
    public Form_Login() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.white);
        
        try {
            this.conn = new ConnectionFactory().getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        //FillCombo();
    }

    public void Access() throws SQLException {

        //String name = (String) name_Combo.getSelectedItem();
        String sql = String.format("select * from login where usuario = ? and senha = ?"); // and nome LIKE '%s'", name_Combo.getSelectedItem()

        pstm = conn.prepareStatement(sql);

        pstm.setString(1, usuario_login.getText());
        pstm.setString(2, pass_login.getText());

        rs = pstm.executeQuery();

        if (rs.next()) {
            String user = rs.getString("usuario");
            String pass = rs.getString("senha");
            String name = rs.getString("nome");
            setNome(name);
            if (autologin.isSelected()) {
                stm = conn.createStatement();
                String sql2 = String.format("UPDATE autologin SET checked = 'TRUE', usuario = '%s', senha = '%s', nome = '%s' WHERE id = '1'", user, pass, name);
                stm.executeUpdate(sql2);
                stm.close();
            } else {
                stm = conn.createStatement();
                String sql2 = String.format("UPDATE autologin SET checked = 'FALSE', usuario = '%s', senha = '%s', nome = '%s' WHERE id = '1'", user, pass, name);
                stm.executeUpdate(sql2);
                stm.close();
            }
            dispose();
            new Form_Sistema().setVisible(true);
            JOptionPane.showMessageDialog(null, "Bem-vindo " + name + "!");
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos.");
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usuario_login = new javax.swing.JTextField();
        pass_login = new javax.swing.JPasswordField();
        pass_restore = new javax.swing.JLabel();
        access_button = new javax.swing.JButton();
        exit_Button = new javax.swing.JButton();
        autologin = new javax.swing.JCheckBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        pass_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_loginActionPerformed(evt);
            }
        });
        pass_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_loginKeyPressed(evt);
            }
        });

        pass_restore.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        pass_restore.setText("Esqueci minha senha");
        pass_restore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass_restoreMouseClicked(evt);
            }
        });

        access_button.setText("Entrar");
        access_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                access_buttonActionPerformed(evt);
            }
        });

        exit_Button.setText("SAIR");
        exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_ButtonActionPerformed(evt);
            }
        });

        autologin.setText("Logar automaticamente");
        autologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autologinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(autologin)
                                .addGap(0, 70, Short.MAX_VALUE))
                            .addComponent(usuario_login)
                            .addComponent(pass_login)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pass_restore, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(access_button)
                                .addGap(18, 18, 18)
                                .addComponent(exit_Button)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usuario_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pass_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass_restore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(autologin)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(access_button)
                    .addComponent(exit_Button))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pass_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_loginActionPerformed

    private void pass_restoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_restoreMouseClicked
        System.out.println("clicou.");        // TODO add your handling code here:
    }//GEN-LAST:event_pass_restoreMouseClicked

    private void exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exit_ButtonActionPerformed

    private void access_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_access_buttonActionPerformed
        try {
            Access();
        } catch (SQLException ex) {
            Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_access_buttonActionPerformed

    private void pass_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_loginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                Access();
            } catch (SQLException ex) {
                Logger.getLogger(Form_Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_pass_loginKeyPressed

    private void autologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autologinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autologinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton access_button;
    private javax.swing.JCheckBox autologin;
    private javax.swing.JButton exit_Button;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pass_login;
    private javax.swing.JLabel pass_restore;
    private javax.swing.JTextField usuario_login;
    // End of variables declaration//GEN-END:variables
}
